version : '3'

services:
  mysql:
    image: mysql:latest

    ports:
      - 3306:3306
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest

    restart: always
    depends_on:
      - mysql

    ports:
      - 8080:80
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: mysql

  app :
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    # command: ["./wait-for-it.sh", "mysql:3306"]

    links:
      - mysql
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8000:8000"

  


